---
- name: Playbook
  roles:
    - common
  hosts: localhost
  gather_facts: false
  vars:
    plan_name: "{{ name }}"
    namespace_key: "{{ key }}"
    src_cluster: klab # pathfinder
    des_cluster: klab
  tasks:
    - name: Switching to source cluster
      shell: |
        oc config use-context {{ src_cluster }}

    - name: Fetch existing Namespaces
      k8s_info:
        api_version: v1
        kind: Namespace
        label_selectors:
          - name = {{ namespace_key }}
      register: namespaces

    - name: Fetch PVCs form all namespaces
      k8s_info:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: "{{ item.metadata.name }}"
      with_items: "{{ namespaces.resources }}"
      register: volumes

    - name: Switching to destination cluster
      shell: |
        oc config use-context {{ des_cluster }}
    
    - name: Network policy tasks
      include_role:
        name: netpol

    - name: Migration plan tasks
      include_role:
        name: plan
