- name: Apply allow ingress network policy
  k8s:
    state: present
    namespace: "{{ item.metadata.name }}"
    definition: "{{ lookup('template', 'templates/netpol-allow-ingress.yaml.j2') | from_yaml }}"
  vars:
    ns_name: "{{ item.metadata.name }}"
  with_items: "{{ namespaces.resources }}"

- name: Apply allow same namespace network policy
  k8s:
    state: present
    namespace: "{{ item.metadata.name }}"
    definition: "{{ lookup('template', 'templates/netpol-allow-same.yaml.j2') | from_yaml }}"
  vars:
    ns_name: "{{ item.metadata.name }}"
  with_items: "{{ namespaces.resources }}"

- name: Apply deny by default network policy
  k8s:
    state: present
    namespace: "{{ item.metadata.name }}"
    definition: "{{ lookup('template', 'templates/netpol-deny-default.yaml.j2') | from_yaml }}"
  vars:
    ns_name: "{{ item.metadata.name }}"
  with_items: "{{ namespaces.resources }}"

- name: Apply Aporeto any to any network policy
  k8s:
    state: present
    namespace: "{{ item.metadata.name }}"
    definition: "{{ lookup('template', 'templates/netpol-apo-any.yaml.j2') | from_yaml }}"
  vars:
    ns_name: "{{ item.metadata.name }}"
  with_items: "{{ namespaces.resources }}"

- name: Apply Aporeto allow ingress network policy
  k8s:
    state: present
    namespace: "{{ item.metadata.name }}"
    definition: "{{ lookup('template', 'templates/netpol-apo-ingress.yaml.j2') | from_yaml }}"
  vars:
    ns_name: "{{ item.metadata.name }}"
  with_items: "{{ namespaces.resources }}"
